# -*- coding: utf-8 -*-
"""10.Multiple Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Uly0JvdIqSXXPzEpwglO-LSVN_YkhHI

# **Multiple Linear Regression**
"""

# importing necessary libraries
import pandas as pd
import numpy as np
from sklearn import linear_model
import math

# importing data
df=pd.read_csv("/content/homeprices.csv")
df

# checking for null values
df.isnull().sum()

"""**Data Preprocessing**

"""

# finding the median
median=math.floor(df.bedrooms.median())
df.bedrooms.median()

# filling the null values with the median
df.bedrooms=df.bedrooms.fillna(median)

"""**Starting with the Linear Regression**"""

# creating an object (instance) of the LinearRegression class from scikit-learn
reg=linear_model.LinearRegression()

"""**Training Data**"""

# training the linear regression model using inputs and outputs defined
reg.fit(df[['area','bedrooms','age']],df.price)

# the model has returned us the coefficients
reg.coef_

# the model has returned us the intercept
reg.intercept_

# testing the model on a new data
area,bedrooms,age=3700,4,18
new_price=pd.DataFrame([[area,bedrooms,age]],columns=['area','bedrooms','age'])
print(f'Price against Area={area}, Bedrooms={bedrooms} and Age={age}: ',reg.predict(new_price))

#can also be written like this
reg.predict([[3700,4,18]])

