# -*- coding: utf-8 -*-
"""17.Random Forests.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GXqWc44LjO8WLatVx_ofpB61ez95tRLn

# **Random Forest**
"""

# impoorting libraries
from sklearn.ensemble import RandomForestClassifier #random Forest Library
from sklearn.tree import DecisionTreeClassifier #decision tree for comparison
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# loading dataset
from sklearn.datasets import load_wine

wine=load_wine()

x,y=wine.data,wine.target

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

"""## **Testing with Decision Tree**"""

dtc=DecisionTreeClassifier(random_state=42)

dtc.fit(x_train,y_train)

y_pred=dtc.predict(x_test)

print("Decision Tree Accuracy: ",accuracy_score(y_test,y_pred))

"""## **Testing with Random Forest**"""

rnf=RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
    random_state=42
    )

rnf.fit(x_test,y_test)

y_pred=rnf.predict(x_test)

print("Random Forest Accuracy: ",accuracy_score(y_test,y_pred))