# -*- coding: utf-8 -*-
"""20.Gradient Boosting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oX-QFyiiEbArSgb3_3lU75Cn09720m5t

# **Gradient Boosting**
"""

# importing libraries
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score,classification_report

cancer=load_breast_cancer()

x,y=cancer.data,cancer.target

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

gb=GradientBoostingClassifier(
    n_estimators=10, #specifiying the number of weak learners
    learning_rate=0.1,
    max_depth=3, #how many splits each tree can make
    random_state=42
)

gb.fit(x_train,y_train)

y_pred=gb.predict(x_test)

print("Accuracy:",accuracy_score(y_test,y_pred))

print("Classification Report:\n",classification_report(y_test,y_pred))

