# -*- coding: utf-8 -*-
"""22.Train/Validation/Test Splits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mysn4Fik2N93oa0Zf2qu8-6E62zCOBrI

# **Train/Validation/Test Splits**
"""

# importing libraries
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

# loading dataset
iris=load_iris()

x,y=iris.data,iris.target

"""### **Splitting into Training/Testing**"""

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

"""### **Splitting Training data into Validation Data**"""

# 0.125 of the 0.8 training data will be used for validation
# 0.125 * 0.8 =0.1, 10%, so 70% training, 20% testing, 10% validation
x_train,x_val,y_train,y_val=train_test_split(x_train,y_train,test_size=0.125,random_state=42)

model=RandomForestClassifier()

model.fit(x_train,y_train)

val_pred=model.predict(x_val)

test_pred=model.predict(x_test)

"""**Testing Accuracy**"""

print("Testing Accuracy: ",accuracy_score(y_test,test_pred))

"""**Validation Accuracy**"""

print("Validation Accuracy: ",accuracy_score(y_val,val_pred))