# -*- coding: utf-8 -*-
"""23.K-Fold Cross-Validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dJnxDE3BJ2Bz3G7QEpMxxj7gGUoMvkLo

# **K-Fold Cross-Validation**
"""

# importing libraries
from sklearn.model_selection import KFold, cross_val_score #cross val score: for the validation score for each fold
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression

# for ignoring warnings
import warnings
warnings.filterwarnings("ignore")

cancer=load_breast_cancer()

x,y=cancer.data,cancer.target

# initializing k folds=5, with shuffle
kfold=KFold(n_splits=5,shuffle=True, random_state=42)

model=LogisticRegression()

# cross validation score, have to give model, k fold and input,outputs as parameters
score=cross_val_score(model,x,y,cv=kfold)

print("Score for Each Fold:",score)

print("Average K-Fold Score:",score.mean())

