# -*- coding: utf-8 -*-
"""6.Matplotlib & Seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uVpDF8mHRFdUL7eLZ3JREi0nr2hYrQYS

# **Matplotlib**
Matplotlib is a basic plotting library in Python. It allows you to create line plots, bar charts, scatter plots, histograms, and more.
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

"""## **Basic Graph**"""

x=[2000,2005,2010,2015,2020,2025]
y=[33,54,67,110,170,267]
y1=[52,85,110,140,200,220]
plt.figure(figsize=(5,3), dpi=120)
plt.plot(x,y, label='Pakistan', color='Olive', marker='^', markersize=6, markeredgecolor='Green')
plt.plot(x,y1, label='India', color='Orange' , marker='^', markersize=6, markeredgecolor='red')
plt.title("Our First Graph", fontdict={'fontname':'serif', 'fontsize':20})
plt.xlabel("Year")
plt.ylabel("Petrol Price")
plt.legend()
plt.savefig('mygraph.png',dpi=150)
# plt.xticks([2000,2002,2005,2007,2010,2012,2015,2017,2020,2022,2025])
# plt.yticks([33,40,54,60,67,90,110,140,170,230,267])
plt.show()

"""## **Bar Chart**"""

labels=['2005','2010','2015','2020','2025']
values=[141,197,300,310,375]
plt.figure(figsize=(5,3),dpi=120)
plt.xlabel('Year')
plt.ylabel('Pakistan GDP')
plt.title("Pakistan GDP Bar Chart")
bars=plt.bar(labels,values,color='g',width=0.5)
for bar in bars:
  bar.set_hatch('o')
# bars[0].set_hatch('.')
# bars[1].set_hatch('-')
# bars[2].set_hatch('/')
# bars[3].set_hatch('*')
# bars[4].set_hatch('o')

plt.show()

