# -*- coding: utf-8 -*-
"""7.Seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wRFtaUR_FX7wBsPr4gxrms2qD5IqZkwc

# **Seaborn**
Seaborn is a Python data visualization library built on top of Matplotlib.

It is designed for making statistical graphics more informative and aesthetically pleasing with minimal code.

Works very well with Pandas DataFrames.
"""

#importing seaborn
import seaborn as sns

#getting different datasets
sns.get_dataset_names()

#importing datasets
tips=sns.load_dataset("tips")
iris=sns.load_dataset("iris")
titanic=sns.load_dataset("titanic")
planets=sns.load_dataset("planets")

tips

"""A **scatter plot** is a type of graph that shows the relationship between two variables using dots (points)."""

# x=x Coordinate
# y=y Coordinate
# data=dataset
# hue=Decides the color grouping.
# size=Controls the marker size.
# palette=Decides the color scheme
sns.scatterplot(x='tip',y='total_bill',data=tips, hue='day',size='size',palette='YlGnBu')

"""A **histogram** is a type of plot that shows the distribution of a single variable by dividing the data into intervals (bins) and counting how many values fall into each bin."""

# kde=it will give us a line over the barb
# bins=tells us how many bars we want for proper precision
sns.histplot(tips['total_bill'],kde=True, bins=20, color='olive')

"""A **distribution graph** is a general term for any graph that shows how values of a variable are spread out (distributed) across a range."""

sns.distplot(tips['tip'],kde=True, bins=20)

"""A **bar chart** is a graph that uses rectangular bars to represent and compare categories of data.

"""

sns.barplot(x='sex',y='tip',data=tips,palette='GnBu',width=0.3)

"""A **boxplot** (also called a whisker plot) is a statistical graph that shows the spread and summary of a dataset."""

sns.boxplot(x='day',y='total_bill',data=tips, hue='sex',palette='GnBu')

"""A **strip plot** is a type of categorical scatter plot in Seaborn that shows individual data points along a single axis for each category."""

# dodge=True will separate the bars,categories
sns.stripplot(x='day',y='total_bill',data=tips, dodge=True, hue='sex',palette='GnBu')

"""A **jointplot** is a specialized plot that shows the relationship between two variables and their distributions at the same time.
scatter+distribution
"""

# kind='kde' = 2D Kernel Density Estimate, showing density of points. (kind=scatter,reg,kde,hex)
# shade=True: Fills the KDE contours with color, giving a solid density area.
# cmap= colormap for the filled KDE plot.
sns.jointplot(x='tip',y='total_bill',data=tips, kind='kde', shade=True, cmap='YlGnBu')

"""A **pairplot** is a grid of plots that shows how all the numerical columns in a dataset relate to each other.

Each column vs column → scatter plot.

The diagonal → shows the distribution of each column (like a mini histogram).

You can also color points by category using hue.
"""

titanic

# titanic.select_dtypes(['number'])= Selects only the numeric columns from the titanic DataFrame
# hue='pclass' = Colors the points according to the passenger class (pclass)
sns.pairplot(titanic.select_dtypes(['number']), hue='pclass')

numeric_data=titanic.select_dtypes(['number']).corr()
numeric_data

"""**Heatmap** = color-coded table → helps you quickly understand patterns, correlations, and outliers in numeric data."""

# annot=True displays the numbers on the heatmap cells; False shows only colors.
sns.heatmap(numeric_data.corr(), annot=True, cmap='coolwarm')

"""A **clustermap** in Seaborn is like a heatmap with clustering:

It shows a heatmap of your data (e.g., correlation or values).

It automatically groups similar rows and columns using hierarchical clustering.

Helps identify patterns, clusters, or groups in your data visually.
"""

sns.clustermap(numeric_data.corr(), annot=True, cmap='coolwarm')

