# -*- coding: utf-8 -*-
"""8.Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VI4Fyvn9AlZqdmaS8KQ0-pgnHuzQg7KO

# **Simple Linear Regression Code**
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# .reshape(-1, 1) converts the 1-D array of shape (5,)
# into a 2-D column vector of shape (5, 1) (required by scikit-learn: X must be 2D: (n_samples, n_features)).
X = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)  # input feature (Study hours)
y = np.array([30, 40, 50, 60, 70])            # target output (Marks)

# Create and train model
model = LinearRegression()
model.fit(X, y)

# Predict values
y_pred = model.predict(X)

# Print slope and intercept
print("Intercept (β0):", model.intercept_)
print("Slope (β1):", model.coef_[0])

# Plotting the data and regression line
plt.scatter(X, y, color='blue', label='Actual Data')
plt.plot(X, y_pred, color='red', linewidth=2, label='Best Fit Line')
plt.xlabel("Study Hours")
plt.ylabel("Marks")
plt.title("Simple Linear Regression")
plt.legend()
plt.show()

