# -*- coding: utf-8 -*-
"""Week-8 Proj-Applying PCA & K-Means.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13J22fZ5XOM2-ZY784W9z5bbMDpc8_X4g

# **Week 8 project: Customer Segmentation**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

data=pd.read_csv('/content/Mall_Customers.csv')

data.head()

x=data[['CustomerID','Annual Income (k$)','Spending Score (1-100)']]

scaler=MinMaxScaler()

scaled_x=scaler.fit_transform(x)

df=pd.DataFrame(scaled_x, columns=x.columns)
df.head()

pca=PCA(n_components=2)

pca_data=pca.fit_transform(scaled_x)

pca.explained_variance_ratio_

kmean=KMeans(n_clusters=4,random_state=42)

clusters=kmean.fit_predict(pca_data)

data['Clusters']=clusters

plt.figure(figsize=(8,8))
plt.scatter(pca_data[:,0],pca_data[:,1], c=clusters, cmap='rainbow', s=60)
plt.title('Customer Segmentation using PCA + K-Means')
plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.legend()
plt.show()

data['Clusters'].value_counts()

print("\nAverage feature values per cluster:")
print(data.groupby('Clusters')[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']].mean())

